// app/api/email/route.ts
import { NextRequest, NextResponse } from 'next/server'
import { Resend } from 'resend'
import { EmailRequest, EmailResponse, OutputType } from '@/types'
import { isValidEmail } from '@/lib/validators'

const OUTPUT_LABELS: Record<OutputType, string> = {
  readme: 'README.md',
  landing: 'Landing Page Copy',
  tweet: 'Tweet Thread',
  producthunt: 'Product Hunt Pitch',
}

export async function POST(request: NextRequest) {
  try {
    const body: EmailRequest = await request.json()
    const { email, outputs } = body

    if (!email || !isValidEmail(email)) {
      return NextResponse.json(
        { error: 'Please enter a valid email address.' },
        { status: 400 }
      )
    }

    if (!outputs || Object.keys(outputs).length === 0) {
      return NextResponse.json({ error: 'No outputs to send.' }, { status: 400 })
    }

    const resend = new Resend(process.env.RESEND_API_KEY)

    const sections = (Object.entries(outputs) as [OutputType, string][])
      .map(
        ([type, content]) => `
        <h2 style="color:#1e293b;border-bottom:1px solid #e2e8f0;padding-bottom:8px;margin-top:32px;">
          ${OUTPUT_LABELS[type]}
        </h2>
        <pre style="background:#f8fafc;padding:16px;border-radius:8px;white-space:pre-wrap;font-size:14px;line-height:1.6;font-family:monospace;">${content}</pre>
      `
      )
      .join('')

    await resend.emails.send({
      from: 'WhatDidIBuild <hello@whatdidibuild.app>',
      to: email,
      subject: 'Your WhatDidIBuild outputs',
      html: `
        <div style="font-family:sans-serif;max-width:700px;margin:0 auto;padding:24px;">
          <h1 style="color:#1e293b;">Your generated outputs</h1>
          <p style="color:#64748b;">Generated by <a href="https://whatdidibuild.app">whatdidibuild.app</a></p>
          ${sections}
          <p style="color:#94a3b8;font-size:12px;margin-top:40px;">
            Sent from <a href="https://whatdidibuild.app">whatdidibuild.app</a>
          </p>
        </div>
      `,
    })

    const response: EmailResponse = { success: true }
    return NextResponse.json(response)
  } catch (error) {
    console.error('Email error:', error)
    return NextResponse.json(
      { error: "Couldn't send the email. Try downloading instead." },
      { status: 500 }
    )
  }
}
